# Stubs for astroid (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from astroid.builder import parse as parse
from astroid.builder import extract_node as extract_node
from astroid.exceptions import *
from astroid.nodes import *
from astroid import node_classes as node_classes
from typing import Any

Load: Any
Store: Any
Del: Any
MANAGER: Any

def inference_tip(infer_function: Any, raise_on_overwrite: bool = ...) -> Any: ...
def register_module_extender(manager: Any, module_name: Any, get_extension_mod: Any) -> Any: ...

BRAIN_MODULES_DIR: Any
