# Stubs for astroid.__pkginfo__ (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

distname: str
modname: str
version: str
numversion: Any
extras_require: Any
install_requires: Any
license: str
author: str
author_email: str
mailinglist: Any
web: str
description: str
classifiers: Any
