# Stubs for astroid.mixins (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from astroid.node_classes import NodeNG
from typing import Any, Iterator, Optional

class BlockRangeMixIn:
    def blockstart_tolineno(self) -> Any: ...

class FilterStmtsMixin:
    def assign_type(self) -> Any: ...

class AssignTypeMixin:
    def assign_type(self) -> Any: ...

class ParentAssignTypeMixin(AssignTypeMixin):
    def assign_type(self) -> Any: ...

class ImportFromMixin(FilterStmtsMixin):
    def do_import_module(self, modname: Optional[Any] = ...) -> Any: ...
    def real_name(self, asname: Any) -> Any: ...

class MultiLineBlockMixin: ...

class NoChildrenMixin:
    def get_children(self) -> Iterator['NodeNG']: ...
